Repository narayan954/dummygram, pull requests merged in 2023-08, with the labels that each got.

#1049 Update README.md
  README.md
Labels: gssoc23, level0

#1065 Use db transaction for post cleanup
  src/components/Post/PostHeader.jsx
Labels: level1, gssoc23

#1067 feat: add sounds effects for theme toggle feature ✨
  src/assets/sounds/index.js
  src/assets/sounds/lightOff.mp3
  src/assets/sounds/lightOn.mp3
  src/js/sounds.jsx
  src/reusableComponents/Darkmode/index.jsx
Labels: level2, gssoc23

#1066 Decline request
  src/components/Notification/index.jsx
  src/components/SideBar/index.jsx
  src/reusableComponents/ShareModal/index.jsx
Labels: level2, gssoc23

#1069 Get dynamic notifcation sender data
  src/components/Notification/index.jsx
  src/pages/Profile/index.jsx
Labels: level2, gssoc23

#1080 Suggestion
  src/App.jsx
  src/components/Post/index.css
  src/components/Suggestions/index.css
  src/components/Suggestions/index.jsx
  src/components/index.js
  src/index.css
Labels: level3, gssoc23

#1088 Story UI
  src/components/Story/index.css
  src/components/Story/index.jsx
  src/pages/Profile/feed/index.css
Labels: level2, gssoc23

#1107 Delete option
  index.html
  src/components/Post/PostHeader.jsx
  src/components/postView/PostDetails.jsx
  src/components/postView/index.jsx
  src/js/deletePost.js
  src/script.js
Labels: level2, gssoc23

#1110 Change theme toggle button to switch
  src/reusableComponents/Darkmode/ToggleSwitch.jsx
  src/reusableComponents/Darkmode/index.css
  src/reusableComponents/Darkmode/index.jsx
Labels: level1, gssoc23

#1111 Profile UI
  src/components/Suggestions/index.css
  src/index.css
  src/pages/Profile/index.css
  src/pages/Profile/index.jsx
Labels: level2, gssoc23

#1112 404 darkmode
  src/pages/NotFound.jsx
Labels: level2, gssoc23

#1120 bug-fix-1113 Enter button
  src/components/postView/index.jsx
Labels: level1, gssoc23

#1122 bug-fix-1114 Emoji issue
  src/components/postView/index.jsx
Labels: level1, gssoc23

#1129 Add message on zero likes
  src/components/Post/index.jsx
Labels: level1, gssoc23

#1126 Moved saved posts from sidebar to profile
  src/App.jsx
  src/components/Favorite.jsx
  src/components/SideBar/index.css
  src/components/SideBar/index.jsx
  src/components/index.js
  src/pages/Profile/index.css
  src/pages/Profile/index.jsx
Labels: level2, gssoc23

#1128 Edit Profile UI
  src/components/EditProfile/index.css
  src/components/EditProfile/index.jsx
  src/components/Navbar/index.css
  src/index.css
Labels: level2, gssoc23

#1133 Add bg zoom in effect on scroll
  src/pages/Profile/index.css
  src/pages/Profile/index.jsx
Labels: level2, gssoc23

#1108 profile and background image cleanup from cloud
  src/components/EditProfile/index.jsx
  src/js/deleteImg.js
  src/pages/Profile/index.jsx
Labels: level2, gssoc23

#1125 card margin and search bar
  src/pages/FooterPages/ContributorPage/ContributorCard.jsx
  src/pages/FooterPages/ContributorPage/index.css
  src/pages/FooterPages/ContributorPage/index.jsx
Labels: level1, gssoc23

#1145 Trim profile dialog box bio
  src/components/ProfileDialogBox/index.jsx
Labels: level1, gssoc23

#1148 Add shimmer on like dialog box
  src/components/Post/DialogBoxSkeleton.jsx
  src/components/Post/LikesDialogBox.jsx
  src/components/Post/index.css
  src/components/ProfileDialogBox/index.jsx
Labels: level1, gssoc23

#1163 Blur bg
  src/pages/Profile/index.css
  src/pages/Profile/index.jsx
Labels: level1, gssoc23

#1167 Delete msg
  src/components/CommunityChat/Reaction/index.jsx
  src/components/CommunityChat/index.css
  src/components/CommunityChat/index.jsx
Labels: level2, gssoc23

#1123 bug-fix-1044 alignment issue
  src/pages/FooterPages/ContributorPage/index.css
Labels: level1, gssoc23

#1173 Added Edit message
  src/components/CommunityChat/index.css
  src/components/CommunityChat/index.jsx
Labels: level2, gssoc23

#1189 fix: Added Margin Property to resolved Gap between Buttons
  src/components/EditProfile/index.jsx
  src/components/SideBar/index.jsx
Labels: level1, gssoc23

#1192 repsonsive post content
  src/pages/Profile/feed/index.css
  src/pages/Profile/feed/index.jsx
Labels: level1, gssoc23

#1186 fix: Replaced WebP File Format with instead of using jpg, png Files Format in Suitable Files
  FlowOfControl.md
  README.md
  index.html
  public/favicon.webp
  src/assets/1.webp
  src/assets/10.webp
  src/assets/11.webp
  src/assets/2.webp
  src/assets/3.webp
  src/assets/4.webp
  src/assets/5.webp
  src/assets/6.webp
  src/assets/7.webp
  src/assets/8.webp
  src/assets/9.webp
  src/assets/about-us.webp
  src/assets/contributors.webp
  src/assets/facebook.svg
  src/assets/goggle.svg
  src/assets/gssoc.webp
  src/assets/guidelines.webp
  src/assets/profile-background.webp
  src/pages/FooterPages/About/index.jsx
  src/pages/FooterPages/ContributorPage/index.jsx
  src/pages/FooterPages/Guidelines/index.jsx
  src/pages/Profile/index.jsx
Labels: level1, gssoc23

#1193 Give a new look to sidebar
  src/components/Post/CommentDialogBox.jsx
  src/components/Post/index.css
  src/components/SideBar/index.css
  src/components/SideBar/index.jsx
Labels: level2, gssoc23

#1212 Help Center page added #1197
  src/App.jsx
  src/components/Caption.jsx
  src/pages/FooterPages/HelpCenter/index.css
  src/pages/FooterPages/HelpCenter/index.jsx
  src/pages/NotFound/index.jsx
  src/pages/index.js
Labels: level1, gssoc23

#1222 Add option to like, comment and share on profile feed hover
  src/pages/Profile/feed/index.css
  src/pages/Profile/feed/index.jsx
Labels: level2, gssoc23

#1224 Post page UI
  .gitignore
  src/components/Post/CommentDialogBox.jsx
  src/components/Post/index.jsx
  src/components/postView/PostViewComments.jsx
  src/components/postView/PostViewMenu.jsx
  src/components/postView/index.css
  src/components/postView/index.jsx
  src/index.css
  src/js/postFn.js
  src/pages/PostView/PostViewStyled.jsx
  src/reusableComponents/ImageSlider/index.css
  src/reusableComponents/ImageSlider/index.jsx
Labels: level3, gssoc23

#1228 chatroom
  src/components/CommunityChat/index.css
  src/components/CommunityChat/index.jsx
  src/index.css
Labels: level2, gssoc23

#1236 My friends
  src/App.jsx
  src/assets/lock.png
  src/components/FriendsComponent/Locked/index.css
  src/components/FriendsComponent/Locked/index.jsx
  src/components/FriendsComponent/index.css
  src/components/FriendsComponent/index.jsx
  src/components/index.js
  src/pages/Friends/index.jsx
  src/pages/Login/index.jsx
  src/pages/Profile/index.jsx
  src/pages/Signup/index.jsx
  src/pages/index.js
Labels: level3, gssoc23

#1233 added edited state
  src/components/CommunityChat/index.css
  src/components/CommunityChat/index.jsx
Labels: level2, gssoc23

#1225 footer added
  src/components/SideBar/index.css
  src/index.css
  src/pages/FooterPages/About/index.jsx
  src/pages/FooterPages/ContributorPage/index.jsx
  src/pages/FooterPages/Feedback/index.jsx
  src/pages/FooterPages/Footer/index.css
  src/pages/FooterPages/Footer/index.jsx
  src/pages/FooterPages/Guidelines/index.jsx
  src/pages/FooterPages/HelpCenter/index.jsx
Labels: level2, gssoc23

#1234 feat(chat): chat ui
  src/components/CommunityChat/Reaction/index.css
  src/components/CommunityChat/index.css
  src/components/CommunityChat/index.jsx
Labels: level2, gssoc23

#1235 telegram like reactions
  src/components/CommunityChat/Reaction/index.jsx
  src/components/CommunityChat/index.css
  src/components/CommunityChat/index.jsx
Labels: level2, gssoc23
