Repository narayan954/dummygram, pull requests merged in 2023-06, with the labels that each got.

#407 Added save favourite option
  src/components/Post.jsx
  src/pages/Profile.jsx
Labels: level3, gssoc23

#441 issue#277 Alert updated
  src/pages/Login.jsx
Labels: level1, gssoc23, Assigned

#428 Issue 414
  src/App.jsx
  src/components/Post.jsx
  src/index.css
  src/reusableComponents/ImageSlider.jsx
Labels: level2, gssoc23

#405 added hover effect in emogi icon
  src/components/Post.jsx
  src/index.css
Labels: no-issue-activity

#390 Fixes #376: Add upload picture from camera
  package-lock.json
  package.json
  src/App.jsx
  src/components/Camera.jsx
  src/components/ImgUpload.jsx
  src/index.css
  src/reusableComponents/Popup.css
  src/reusableComponents/Popup.jsx
Labels: level3, gssoc23

#382 Text Entered by User Should be Line breaked as it is he entered
  src/index.css
Labels: no-issue-activity

#448 fixed [#446]
  src/App.jsx
Labels: level1, gssoc23

#437 Added sidebar frontend
  package-lock.json
  src/App.jsx
  src/components/Favorite.jsx
  src/components/SideBar.css
  src/components/SideBar.jsx
  src/index.css
  src/pages/Profile.jsx
Labels: level3, gssoc23

#452 Post Uploading Criteria Changed Completely
  src/App.jsx
  src/components/ImgUpload.jsx
  src/components/SideBar.css
  src/components/SideBar.jsx
  src/index.css
Labels: level3, gssoc23

#447 #445-favourite section
  src/App.jsx
  src/components/Post.jsx
Labels: level1, gssoc23

#478 Add double click to like feature #464
  src/components/Post.jsx
  src/reusableComponents/ImageSlider.jsx
Labels: level1, gssoc23

#485 fixed[#484]
  src/reusableComponents/ImageSlider.css
Labels: level1, gssoc23

#492 Seperate CSS from index.js and add them to their own folder
  src/assets/postbg.avif
  src/components/Camera/index.css
  src/components/Camera/index.jsx
  src/components/Favorite.jsx
  src/components/ImgUpload/index.css
  src/components/ImgUpload/index.jsx
  src/components/Loader/index.css
  src/components/Loader/index.jsx
  src/components/NotFound.jsx
  src/components/Post/index.css
  src/components/Post/index.jsx
  src/components/ReadMore/index.css
  src/components/ReadMore/index.jsx
  src/components/SideBar/index.css
  src/components/SideBar/index.jsx
  src/components/imgPreview.css
  src/index.css
  src/pages/Login/index.css
  src/pages/Login/index.jsx
  src/pages/Profile/index.css
  src/pages/Profile/index.jsx
  src/pages/Signup/index.css
  src/pages/Signup/index.jsx
  src/reusableComponents/DialogBox/index.jsx
  src/reusableComponents/ImageSlider/index.css
  src/reusableComponents/ImageSlider/index.jsx
  src/reusableComponents/Popup/index.css
  src/reusableComponents/Popup/index.jsx
Labels: level3, gssoc23

#500 Dp zoom in feature added
  src/App.jsx
  src/components/Favorite.jsx
  src/components/ImgUpload/index.jsx
  src/components/SideBar/index.jsx
  src/pages/Profile/index.jsx
  src/reusableComponents/AnimatedButton.jsx
  src/reusableComponents/ShareModal.jsx
  src/reusableComponents/SnackBar.jsx
Labels: level1, gssoc23

#498 Resolve the working of multi column layout in favourites page
  src/App.jsx
  src/components/Favorite.jsx
  src/components/Navbar/index.jsx
  src/hooks/useRowMode.jsx
Labels: level2, gssoc23

#517 Add profile feed section
  src/pages/Profile/index.css
  src/pages/Profile/index.jsx
Labels: level2, gssoc23

#524 Resolved Download text posts bug
  src/components/Post/index.jsx
Labels: level1, gssoc23

#506 Improve post UI/UX
  src/components/Post/index.css
  src/components/Post/index.jsx
  src/components/ReadMore/index.jsx
  src/reusableComponents/Flexbetween.jsx
Labels: level3, gssoc23

#533 fixed: alignment of signup div
  src/App.jsx
Labels: level1, gssoc23

#532 #496: Profile page issue
  src/App.jsx
  src/components/Navbar/index.jsx
  src/pages/Profile/index.jsx
Labels: level2, gssoc23

#539 Refactor codebase
  src/App.jsx
  src/components/Favorite.jsx
  src/components/ImgUpload/Camera/index.css
  src/components/ImgUpload/Camera/index.jsx
  src/components/ImgUpload/index.jsx
  src/components/Navbar/index.css
  src/components/Navbar/index.jsx
  src/components/Post/CommentBox.jsx
  src/components/Post/CommentDialogBox.jsx
  src/components/Post/CommentHolder.jsx
  src/components/Post/ImgBox.jsx
  src/components/Post/PostHeader.jsx
  src/components/Post/PostNav.jsx
  src/components/Post/index.css
  src/components/Post/index.jsx
  src/components/SideBar/index.jsx
  src/components/index.js
  src/index.css
  src/pages/Login/index.css
  src/pages/Login/index.jsx
  src/pages/PostView/index.jsx
  src/pages/Profile/index.jsx
  src/pages/Signup/index.css
  src/pages/Signup/index.jsx
  src/pages/index.js
  src/reusableComponents/AnimatedButton.jsx
  src/reusableComponents/DialogBox/index.jsx
  src/reusableComponents/Loader/index.css
  src/reusableComponents/Loader/index.jsx
  src/reusableComponents/Popup/index.jsx
  src/reusableComponents/ShareModal/index.css
  src/reusableComponents/ShareModal/index.jsx
  src/reusableComponents/SnackBar.jsx
  src/reusableComponents/index.js
Labels: level3, gssoc23

#501 Updated Add friend request button and notification button
  src/App.jsx
  src/components/Notifications.jsx
  src/components/Post/Caption.jsx
  src/components/Post/PostHeader.jsx
  src/components/Post/index.jsx
  src/components/SideBar/index.jsx
  src/components/index.js
  src/pages/Profile/index.jsx
Labels: level2, gssoc23

#519 new styles and features added
  src/index.css
  src/reusableComponents/ImageSlider/index.css
Labels: invalid

#550 Add unique username for users
  src/App.jsx
  src/pages/Profile/index.jsx
  src/pages/Signup/index.css
  src/pages/Signup/index.jsx
Labels: level3, gssoc23

#570 Enhanced Add to favourite feature
  src/components/Post/PostNav.jsx
Labels: level1, gssoc23

#583 Improved postview page
  public/assets/postbg.webp
  src/components/ReadMore/index.jsx
  src/components/postView/PostDetails.jsx
  src/components/postView/PostViewComments.jsx
  src/components/postView/PostViewMenu.jsx
  src/components/postView/index.jsx
  src/index.css
  src/pages/PostView/PostViewStyled.jsx
  src/pages/PostView/index.jsx
  src/reusableComponents/ImageSlider/index.css
  src/reusableComponents/ImageSlider/index.jsx
Labels: level2, gssoc23

#592 Fix email issue
  src/pages/Profile/index.jsx
Labels: level1, gssoc23

#594 Implemented dark mode
  index.html
  src/App.jsx
  src/components/Favorite.jsx
  src/components/Notifications.jsx
  src/components/Post/CommentBox.jsx
  src/components/Post/CommentHolder.jsx
  src/components/Post/ImgBox.jsx
  src/components/Post/PostHeader.jsx
  src/components/Post/PostNav.jsx
  src/components/Post/index.css
  src/components/Post/index.jsx
  src/components/ReadMore/index.jsx
  src/components/SideBar/index.css
  src/components/SideBar/index.jsx
  src/index.css
  src/pages/Login/index.jsx
  src/pages/Profile/index.css
  src/pages/Profile/index.jsx
  src/pages/Signup/index.css
  src/reusableComponents/Darkmode/Darkmode.jsx
  src/reusableComponents/Darkmode/darkmode.css
  src/reusableComponents/index.js
  src/script.js
Labels: level3, gssoc23

#573 New UI for comment section
  src/components/Post/CommentBox.jsx
  src/components/Post/CommentDialogBox.jsx
  src/components/Post/index.css
  src/components/Post/index.jsx
  src/pages/NotFound.jsx
  src/reusableComponents/DialogBox/index.jsx
Labels: level3, gssoc23
