Repository narayan954/dummygram, pull requests merged in 2023-03, with the labels that each got.

#227 Fixes #133 [`Cypress`]
  cypress.config.js
  cypress/e2e/spec.cy.js
  cypress/fixtures/example.json
  cypress/support/commands.js
  cypress/support/e2e.js
  package-lock.json
  package.json
Labels: hard, jwoc

#246 Signup page look enhansed
  package-lock.json
  package.json
  src/index.css
  src/pages/Signup.jsx
Labels: medium, jwoc

#250 made the navbar sticky
  src/App.jsx
  src/index.css
Labels: easy, jwoc
