Repository narayan954/dummygram, pull requests merged in 2023-07, with the labels that each got.

#602 added number of posts
  src/pages/Profile/index.jsx
Labels: level1, gssoc23

#606 Set loader for favourites page
  src/components/Favorite.jsx
Labels: level2, gssoc23

#617 New Post UI Created and Responsiveness Added
  src/components/ImgUpload/Camera/index.css
  src/components/ImgUpload/Camera/index.jsx
  src/components/ImgUpload/index.css
  src/components/ImgUpload/index.jsx
  src/components/SideBar/index.css
  src/components/SideBar/index.jsx
  src/reusableComponents/Popup/index.css
Labels: level3

#618 Add feedback page using email js library
  package-lock.json
  package.json
  src/App.jsx
  src/components/SideBar/Footer.jsx
  src/pages/Feedback/index.css
  src/pages/Feedback/index.jsx
  src/pages/index.js
Labels: level2, gssoc23

#568 added feature of forgot password
  .env
  package-lock.json
  src/App.jsx
  src/components/LandingAnimation.jsx
  src/index.css
  src/pages/ForgotPassword.jsx
  src/pages/Login/index.css
  src/pages/Login/index.jsx
  src/pages/Profile/index.css
  src/pages/Profile/index.jsx
  src/pages/Signup/index.css
  src/pages/Signup/index.jsx
Labels: level2, gssoc23

#622 Redirect user when click on read more
  src/components/Post/ImgBox.jsx
  src/components/Post/index.jsx
  src/components/ReadMore/index.jsx
  src/components/postView/index.jsx
Labels: level2, gssoc23

#613 1)modified user Schema to have subcollections, 2)added friend request…
  package.json
  src/components/ImgUpload/index.jsx
  src/components/Navbar/index.jsx
  src/components/Notifications.jsx
  src/components/Post/PostHeader.jsx
  src/components/postView/index.jsx
  src/index.css
  src/lib/firebase.js
  src/pages/Login/index.jsx
  src/pages/Profile/index.jsx
  src/pages/Signup/index.jsx
  src/reusableComponents/Darkmode/index.css
  src/reusableComponents/Darkmode/index.jsx
  src/reusableComponents/index.js
Labels: level3, gssoc23

#577 Searchfile added
  package-lock.json
  package.json
  src/App.jsx
  src/components/SearchBar/index.css
  src/components/SearchBar/index.jsx
  src/components/SideBar/index.jsx
  src/components/index.js
Labels: level3, gssoc23

#625 Added profile Image to the sidebar
  package-lock.json
  package.json
  src/components/SideBar/index.css
  src/components/SideBar/index.jsx
Labels: level1, gssoc23

#626 Added dark mode in the lower section of sidebar
  src/components/SideBar/Footer.jsx
  src/components/SideBar/index.css
Labels: level1, gssoc23

#624 Improve the login page
  src/assets/login-right.webp
  src/components/Navbar/index.jsx
  src/pages/Login/index.css
  src/pages/Login/index.jsx
Labels: level2, gssoc23

#631 New logo Added
  README-HINDI.md
  README.md
  src/App.jsx
  src/assets/app-logo.png
  src/assets/logo.png
  src/assets/logo.webp
  src/components/Navbar/index.css
  src/components/Navbar/index.jsx
  src/index.css
  src/pages/About/index.css
  src/pages/About/index.jsx
  src/pages/ForgotPassword.jsx
  src/pages/Login/index.jsx
Labels: level1, gssoc23

#644 Create guidelines page for dummygram
  src/App.jsx
  src/pages/FooterPages/About/index.css
  src/pages/FooterPages/About/index.jsx
  src/pages/FooterPages/Feedback/index.css
  src/pages/FooterPages/Feedback/index.jsx
  src/pages/FooterPages/Guidelines/index.css
  src/pages/FooterPages/Guidelines/index.jsx
  src/pages/FooterPages/design.css
  src/pages/index.js
Labels: level3, gssoc23

#653 Fix likecount bug on favourite page
  src/components/Post/index.jsx
Labels: level1, gssoc23

#657 Create a better UI for notification page
  src/App.jsx
  src/components/Favorite.jsx
  src/components/Notification/index.css
  src/components/Notification/index.jsx
  src/components/index.js
  src/pages/Profile/index.jsx
  src/pages/Signup/index.jsx
Labels: level2, gssoc23

#666 Fix data lose that was happening due to creating post
  src/components/ImgUpload/index.jsx
Labels: level2, gssoc23

#674 Improved UI of login page
  src/pages/Login/index.css
  src/pages/Login/index.jsx
Labels: level1, gssoc23

#688 Add contributor page and fix some minor issues
  src/App.jsx
  src/components/Navbar/index.jsx
  src/components/SettingsComponents/Sidebar/index.jsx
  src/components/SideBar/Footer.jsx
  src/pages/FooterPages/ContributorPage/ContributorCard.jsx
  src/pages/FooterPages/ContributorPage/index.css
  src/pages/FooterPages/ContributorPage/index.jsx
  src/pages/FooterPages/design.css
  src/pages/Profile/index.css
  src/reusableComponents/index.js
Labels: level1, gssoc23

#700 setting page sidebar icon
  src/components/SettingsComponents/Sidebar/index.css
  src/components/SettingsComponents/Sidebar/index.jsx
Labels: level2, gssoc23

#708 Add pagination in contributors page
  src/pages/FooterPages/ContributorPage/index.jsx
Labels: level2, gssoc23

#722 issue #714 unhandled promise
  src/pages/FooterPages/About/index.jsx
  src/pages/Profile/index.jsx
  src/pages/Signup/index.jsx
Labels: level1, gssoc23

#686 improve sign up page ui
  src/assets/blank-profile.webp
  src/pages/Login/index.css
  src/pages/Login/index.jsx
  src/pages/Profile/index.jsx
  src/pages/Signup/index.jsx
Labels: level2, gssoc23

#746 Fixed: Posting empty comments
  src/components/Post/CommentBox.jsx
  src/components/Post/CommentHolder.jsx
  src/components/postView/index.jsx
Labels: level1, gssoc23

#643 Improved Post UI
  src/components/ImgUpload/index.css
  src/components/Post/CommentBox.jsx
  src/components/Post/CommentDialogBox.jsx
  src/components/Post/CommentHolder.jsx
  src/components/Post/ImgBox.jsx
  src/components/Post/PostHeader.jsx
  src/components/Post/PostNav.jsx
  src/components/Post/index.css
  src/components/Post/index.jsx
  src/components/ReadMore/index.css
  src/components/SearchBar/index.jsx
  src/components/postView/index.jsx
  src/index.css
  src/lib/firebase.js
  src/pages/FooterPages/About/index.jsx
  src/pages/FooterPages/ContributorPage/index.jsx
  src/pages/FooterPages/Feedback/index.jsx
  src/pages/FooterPages/Guidelines/index.jsx
  src/pages/Profile/index.jsx
  src/pages/Signup/index.jsx
  src/reusableComponents/ImageSlider/index.css
  src/reusableComponents/ImageSlider/index.jsx
Labels: level2, gssoc23

#759 Improve UI of comment box
  src/components/Post/CommentBox.jsx
  src/components/Post/CommentDialogBox.jsx
  src/components/Post/CommentHolder.jsx
  src/components/Post/index.css
  src/components/Post/index.jsx
  src/components/SearchBar/index.jsx
  src/components/postView/index.jsx
  src/lib/firebase.js
  src/pages/FooterPages/About/index.jsx
  src/pages/FooterPages/ContributorPage/index.jsx
  src/pages/FooterPages/Feedback/index.jsx
  src/pages/Profile/index.jsx
  src/pages/Signup/index.jsx
  src/reusableComponents/DialogBox/index.jsx
Labels: level2, gssoc23

#765 made home page ui responsive
  src/App.jsx
  src/components/SideBar/index.css
  src/index.css
  src/pages/Profile/index.css
Labels: level2, gssoc23

#812 Add char limit on different input fields
  src/components/ImgUpload/index.jsx
  src/components/Post/CommentBox.jsx
  src/components/SideBar/index.jsx
  src/pages/Login/index.jsx
  src/pages/Signup/index.jsx
  src/reusableComponents/Auth/Auth__pass__input.jsx
  src/reusableComponents/Auth/Auth__text__input.jsx
Labels: level1, gssoc23

#821 Improvement in form ui + buttons for signup and login form both
  src/index.css
  src/pages/Login/index.css
  src/pages/Signup/index.css
  src/pages/Signup/index.jsx
  src/reusableComponents/Auth/Auth_container.jsx
Labels: level2, gssoc23

#836 Fix formatting in README
  README.md
Labels: level1, gssoc23

#832 added sidebar in post page
  src/components/postView/index.jsx
  src/index.css
  src/pages/PostView/PostViewStyled.jsx
  src/pages/PostView/index.jsx
Labels: level2, gssoc23

#841 Modified dummygram logo
  src/App.jsx
  src/components/Navbar/index.css
  src/components/Navbar/index.jsx
  src/index.css
  src/pages/Login/index.jsx
  src/pages/Profile/index.css
  src/pages/Signup/index.jsx
  src/reusableComponents/Auth/Auth__top.jsx
  src/reusableComponents/Auth/index.js
  src/reusableComponents/Logo/index.css
  src/reusableComponents/Logo/index.jsx
  src/reusableComponents/index.js
Labels: level1, gssoc23

#852 Old Post image updation
  src/App.jsx
  src/components/ImgUpload/index.jsx
  src/components/Post/PostHeader.jsx
  src/components/Post/PostNav.jsx
  src/components/SideBar/index.jsx
  src/index.css
  src/pages/PostView/PostViewStyled.jsx
  src/pages/Profile/index.jsx
  src/reusableComponents/Logo/index.jsx
Labels: level3, gssoc23

#871 theme-bug-647 theme button change
  src/App.jsx
  src/components/Navbar/index.css
  src/components/Navbar/index.jsx
  src/index.css
  src/reusableComponents/Darkmode/index.css
  src/reusableComponents/Darkmode/index.jsx
Labels: level1, gssoc23

#881 Profile dialog box
  src/components/Post/PostHeader.jsx
  src/components/ProfileDialogBox/index.css
  src/components/ProfileDialogBox/index.jsx
  src/index.css
  src/reusableComponents/ErrorBoundary/index.jsx
Labels: level2, gssoc23

#917 fixed nav icons color on hovering
  src/index.css
Labels: level1, gssoc23

#924 changes made in eye icon
  src/pages/Login/index.css
  src/pages/Signup/index.css
Labels: level1, gssoc23

#937 Fix loader bug of profile page
  src/pages/Profile/index.jsx
Labels: level1, gssoc23

#935 Edit profile
  src/components/EditProfile/index.css
  src/components/EditProfile/index.jsx
  src/components/Navbar/index.css
  src/components/Navbar/index.jsx
  src/components/Post/PostHeader.jsx
  src/components/Post/PostNav.jsx
  src/components/Post/index.jsx
  src/components/ProfileDialogBox/index.jsx
  src/components/SideBar/index.jsx
  src/components/index.js
  src/pages/Profile/index.jsx
Labels: level2, gssoc23

#951 Guidelines Page UI
  src/assets/guidelines.png
  src/pages/FooterPages/About/index.css
  src/pages/FooterPages/About/index.jsx
  src/pages/FooterPages/Guidelines/index.css
  src/pages/FooterPages/Guidelines/index.jsx
  src/pages/FooterPages/design.css
Labels: level2, gssoc23

#956 Story feature
  src/components/ImgUpload/index.css
  src/components/ImgUpload/index.jsx
  src/components/Post/index.jsx
  src/components/SideBar/index.jsx
  src/components/Story/index.css
  src/components/Story/index.jsx
  src/components/index.js
  src/pages/Profile/index.css
  src/pages/Profile/index.jsx
  src/reusableComponents/ImageSlider/index.jsx
Labels: level3, gssoc23

#965 Sound page overlap fixed
  src/components/SettingsComponents/Sounds/index.css
Labels: level1, gssoc23

#969 Contributors
  src/assets/contributors.png
  src/index.css
  src/pages/FooterPages/ContributorPage/ContributorCard.jsx
  src/pages/FooterPages/ContributorPage/index.css
  src/pages/FooterPages/ContributorPage/index.jsx
Labels: level2, gssoc23

#967 Add user's name on chat
  src/components/CommunityChat/index.css
  src/components/CommunityChat/index.jsx
Labels: level1, gssoc23

#968 Fixed comment box error
  src/reusableComponents/DialogBox/index.jsx
Labels: level2, gssoc23

#973 Changes in Dark Theme
  src/App.jsx
  src/components/ImgUpload/Camera/index.css
  src/components/ImgUpload/index.css
  src/components/Navbar/index.css
  src/components/Post/index.css
  src/components/Post/index.jsx
  src/components/SideBar/Footer.jsx
  src/components/SideBar/index.css
  src/components/SideBar/index.jsx
  src/index.css
  src/pages/Profile/index.jsx
  src/reusableComponents/DialogBox/index.jsx
  src/reusableComponents/Logo/index.css
Labels: level1, gssoc23

#974 feat: added emojipicker in chat
  package-lock.json
  package.json
  src/components/CommunityChat/index.css
  src/components/CommunityChat/index.jsx
  src/components/Post/index.jsx
  src/index.css
Labels: level1, gssoc23

#993 profile dialog box ui and dummy data
  src/components/Post/PostHeader.jsx
  src/components/ProfileDialogBox/index.css
  src/components/ProfileDialogBox/index.jsx
Labels: level2, gssoc23

#998 Search user
  .prettierrc
  src/components/CommunityChat/index.jsx
  src/components/SearchBar/index.css
  src/components/SearchBar/index.jsx
Labels: level2, gssoc23

#933 bug fix for comment delete button issue number #914
  src/components/Post/CommentDialogBox.jsx
  src/components/Post/ImgBox.jsx
  src/components/Post/index.jsx
Labels: level1, gssoc23

#983 add profile grid view
  src/pages/Profile/feed/index.css
  src/pages/Profile/feed/index.jsx
  src/pages/Profile/index.css
  src/pages/Profile/index.jsx
Labels: level2, gssoc23

#985 setup pagination for chat room
  src/components/CommunityChat/index.css
  src/components/CommunityChat/index.jsx
Labels: level2, gssoc23

#1016 add time on chat
  src/components/CommunityChat/index.css
  src/components/CommunityChat/index.jsx
Labels: level1, gssoc23

#1026 bug fix for emoji issue #737
  src/components/Post/index.jsx
  src/reusableComponents/DialogBox/index.jsx
Labels: level1, gssoc23

#1029 Readmore
  src/components/Post/ImgBox.jsx
  src/components/ReadMore/index.jsx
Labels: level1, gssoc23

#975 Post liker list
  src/components/Post/LikesDialogBox.jsx
  src/components/Post/index.css
  src/components/Post/index.jsx
  src/reusableComponents/DialogBox/index.css
  src/reusableComponents/DialogBox/index.jsx
Labels: level3, gssoc23

#1010 search Feature added issue #999
  src/components/Story/index.jsx
  src/pages/FooterPages/ContributorPage/index.css
  src/pages/FooterPages/ContributorPage/index.jsx
Labels: level2, gssoc23

#1038 Add dropdown menu in sidebar
  src/components/ImgUpload/index.jsx
  src/components/Post/CommentDialogBox.jsx
  src/components/Post/index.jsx
  src/components/SideBar/index.css
  src/components/SideBar/index.jsx
  src/pages/Profile/index.jsx
Labels: level2, gssoc23

#1039 Update username regex
  src/components/EditProfile/index.jsx
  src/pages/Signup/index.jsx
Labels: level1, gssoc23

#1040 Fix notif page console error
  src/components/Notification/index.jsx
Labels: level1, gssoc23

#1042 Fix name highlight on notification page
  src/components/Notification/index.jsx
  src/pages/Profile/index.jsx
Labels: level1, gssoc23

#1050 Fixed responsiveness, look and visibililty of search box
  src/components/Navbar/index.css
  src/components/Navbar/index.jsx
  src/components/SearchBar/index.css
  src/components/SearchBar/index.jsx
Labels: level1, gssoc23

#1051 Add shimmer effect on posts
  src/App.jsx
  src/main.jsx
  src/pages/PostView/index.jsx
  src/pages/Profile/index.jsx
  src/reusableComponents/ErrorBoundary/index.jsx
  src/reusableComponents/PostSkeleton/index.css
  src/reusableComponents/PostSkeleton/index.jsx
  src/reusableComponents/index.js
Labels: level2, gssoc23

#1052 Add click away listener on all components
  src/components/CommunityChat/Reaction/index.jsx
  src/components/CommunityChat/index.jsx
  src/components/EditProfile/index.jsx
  src/components/SideBar/index.jsx
  src/pages/Profile/index.jsx
Labels: level2, gssoc23

#1053 Add loader on chat page
  src/components/CommunityChat/index.css
  src/components/CommunityChat/index.jsx
Labels: level1, gssoc23

#1056 Edit background img feature
  src/components/SideBar/index.css
  src/pages/Profile/index.css
  src/pages/Profile/index.jsx
Labels: level2, gssoc23
